logging.config: classpath:log4j2-production.yml

# App variable
app:
  var:
    context-root: /setshr
    base-path: /home/projects/setshr/be
    host: https://suiteadmin.joinbusinessmc.com
    mailpath: 
    cors-url: http://15.188.23.10, http://suiteadmin.joinbusinessmc.com, ${app.var.host}
    database-name: setshr
    database-host: localhost
    database-port: 3306
    database-params: "&serverTimezone=Europe/Rome&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true"
    database-username: setshr-user
    database-password: MySqlsetshr_123%
    server-port: 8080
    ddl-auto: true
    ssl-enabled: false
    mail-send-enabled: true
    user-avatar:
      location: ${app.var.base-path}/user-avatar-image
    maindocument:
      location: ${app.var.base-path}/maindocument-upload
    monthly-report-check:
      enabled: true
      first-scheduled-cron: "0 0 19 2 1/1 ?" 
      second-scheduled-cron: "0 0 19 4 1/1 ?"
      third-scheduled-cron: "0 0 19 6 1/1 ?"
      zero-scheduled-cron: "0 0 19 L 1/1 ?"
      enabled-test: false
      test-scheduled-cron: "0 0 18 14 1/1 ?"
